pre-installation brotli
brotli needed, but not installed by itself.  Maybe you forgot to include it in the dependencies?
If it is not installed, an error occurs:
```
Traceback (most recent call last):
  File ".../python3.9/site-packages/sbeaver/sbeaver.py", line 12, in <module>
    import brotli
ModuleNotFoundError: No module named 'brotli'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File ".../mecli/./main.py", line 3, in <module>
    import sbeaver
  File ".../python3.9/site-packages/sbeaver/__init__.py", line 1, in <module>
    from .sbeaver import Server
  File ".../python3.9/site-packages/sbeaver/sbeaver.py", line 14, in <module>
    if not main_server.silence:
NameError: name 'main_server' is not defined
```